### ISSUE TITLE
A question about the mixed feture

### ISSUE THREAD

**Issue by sunhao12121** [zhanglichao/updatenet#17]
thank you for your elegant work. I have a question about the updateNet. When we use the Gaussian filter， actually we use the  convolution  to calculate the similarity between the template and the search. With the updateNet, if it is possible to produce noise when the Net mix the different template without adding channel or change the storage function.   I really want to know how can updateNet mix different template in one feature, maybe I haven't totally understand the structure  of your work. Look forward to your reply

**Comment by zhanglichao** [comment]
hi
 
Thanks for your interest, and it is proposed by a good question.
Yes, we input three different templates into UpdateNet, which predicts the learned template isotropic as the accumulated template. Instead of the learning the total features, we learn the difference of templates by a residual learning method, which is carefully described in the paper. By this training mechanism, the Network could learn a good template exactly similar as the real one.

**Comment by sunhao12121** [comment]
thanks for your reply
